package com.baylorw.branchtest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The response to https://api.github.com/users/${userName}
 * We don't use most of these properties but leaving them because they might be useful for debugging.
 * <p>
 * File generated by https://www.jsonschema2pojo.org/
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({"login", "id", "node_id", "avatar_url", "gravatar_id", "url", "html_url", "followers_url", "following_url", "gists_url", "starred_url", "subscriptions_url", "organizations_url", "repos_url", "events_url", "received_events_url", "type", "user_view_type", "site_admin", "name", "company", "blog", "location", "email", "hireable", "bio", "twitter_username", "public_repos", "public_gists", "followers", "following", "created_at", "updated_at"})
public class GitHubUser {
    @JsonProperty("login")
    public String login;
    @JsonProperty("id")
    public Integer id;
    @JsonProperty("node_id")
    public String nodeId;
    @JsonProperty("avatar_url")
    public String avatarUrl;
    @JsonProperty("gravatar_id")
    public String gravatarId;
    @JsonProperty("url")
    public String url;
    @JsonProperty("html_url")
    public String htmlUrl;
    @JsonProperty("followers_url")
    public String followersUrl;
    @JsonProperty("following_url")
    public String followingUrl;
    @JsonProperty("gists_url")
    public String gistsUrl;
    @JsonProperty("starred_url")
    public String starredUrl;
    @JsonProperty("subscriptions_url")
    public String subscriptionsUrl;
    @JsonProperty("organizations_url")
    public String organizationsUrl;
    @JsonProperty("repos_url")
    public String reposUrl;
    @JsonProperty("events_url")
    public String eventsUrl;
    @JsonProperty("received_events_url")
    public String receivedEventsUrl;
    @JsonProperty("type")
    public String type;
    @JsonProperty("user_view_type")
    public String userViewType;
    @JsonProperty("site_admin")
    public Boolean siteAdmin;
    @JsonProperty("name")
    public String name;
    @JsonProperty("company")
    public String company;
    @JsonProperty("blog")
    public String blog;
    @JsonProperty("location")
    public String location;
    @JsonProperty("email")
    public String email;
    @JsonProperty("hireable")
    public Object hireable;
    @JsonProperty("bio")
    public Object bio;
    @JsonProperty("twitter_username")
    public String twitterUsername;
    @JsonProperty("public_repos")
    public Integer publicRepos;
    @JsonProperty("public_gists")
    public Integer publicGists;
    @JsonProperty("followers")
    public Integer followers;
    @JsonProperty("following")
    public Integer following;

    //--- Since i don't plan to do math on these, i'm leaving the dates as strings.
    @JsonProperty("created_at")
    public String createdAt;
    @JsonProperty("updated_at")
    public String updatedAt;
}